### ISSUE TITLE
How to download release?

### ISSUE THREAD

**Issue by station72** [contentstack/contentstack-dotnet#17]
Hello! 
How can I download the whole release from the ContentStack? 
https://www.contentstack.com/docs/developers/apis/content-management-api/?locale=europe#get-all-items-in-a-release

There is no API for the endpoint in this .Net package, but maybe I can see some example with calling ContentStack endpoints not via package?

**Comment by uttamukkoji** [comment]
Hi @station72 ,

Thanks for raising issue.

contentstack-dotnet package is specific to **Content Delivery API**, and the API that you mentioned is part of **Content Management API**.

We have the separation of this API, as **Content Delivery API** only require API Key, Delivery token and Environment, and **Content Management API** requires user auth-token. 

Because of above mentioned reason this package only support CDA. 

You can use [Contentstack-Managment-Javascript](https://github.com/contentstack/contentstack-management-javascript) [NPM](https://www.npmjs.com/package/@contentstack/management) package that support Content Management API.

We hope this details will be helpful to you. 

We are closing this issue as the requested API is not part of CDA. If you have any concern or issue you can create new issue on Contentstack DotNet repository.
